version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:5.1.2
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-manager:
    image: dddpaul/kafka-manager:1.3.3.22
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    command:
      - "kafka-manager-1.3.3.22/bin/kafka-manager"
      - "-J-XX:+PrintCommandLineFlags"
      - "-J-XX:+PrintGCDetails"
      - "-J-XX:+PrintGCDateStamps"
      - "-J-XX:+HeapDumpOnOutOfMemoryError"
      - "-J-XX:+UseConcMarkSweepGC"
      - "-J-XX:+UseParNewGC"
      - "-Dapplication.features.0=KMClusterManagerFeature"
      - "-Dapplication.features.1=KMTopicManagerFeature"
      - "-Dapplication.features.2=KMPreferredReplicaElectionFeature"
      - "-Dapplication.features.3=KMReassignPartitionsFeature"

  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.1.2
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_HOST_NAME: kafka-rest

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:5.1.2
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: "http://localhost:8081"

  kafka-ui:
    image: landoop/kafka-topics-ui:0.9.3
    depends_on:
      - zookeeper
      - kafka
      - kafka-rest
    ports:
      - 9001:8000
    environment:
      KAFKA_REST_PROXY_URL: http://kafka-rest:8082
      PROXY: "true"
