version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:1.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 10000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    image: sheepkiller/kafka-manager:1.3.1.8
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181

  kafka-rest:
    image: confluentinc/cp-kafka-rest:4.0.0-3
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_HOST_NAME: kafka-rest

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:4.0.0-3
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: "http://localhost:8081"

  kafka-ui:
    image: landoop/kafka-topics-ui:0.9.3
    depends_on:
      - zookeeper
      - kafka
      - kafka-rest
    ports:
      - 9001:8000
    environment:
      KAFKA_REST_PROXY_URL: http://kafka-rest:8082
      PROXY: "true"
