version: "2"

services:

  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
    network_mode: "host"

  kafka:
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    network_mode: "host"

  schema-registry:
    image: confluent/schema-registry
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"
    environment:
      SR_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
    network_mode: "host"

  rest-proxy:
    image: confluent/rest-proxy
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    ports:
      - "8082:8082"
    environment:
      RP_ZOOKEEPER_CONNECT: "zookeeper:2181"
      RP_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    network_mode: "host"

  kafka-manager:
    image: sheepkiller/kafka-manager:1.3.1.8
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"

  kafka-ui:
    image: landoop/kafka-topics-ui:0.9.3
    ports:
      - "9001:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://rest-proxy:8082"
      PROXY: "true"
